- name: Get Swarm leader from inventory
  set_fact:
    swarm_leader: "{{ groups[group_name] | map('extract', hostvars) | selectattr('is_swarm_leader', 'defined') | selectattr('is_swarm_leader', 'equalto', true) | map(attribute='inventory_hostname') | list | first }}"

- name: Synchronize /opt/certificates directory from swarm leader to all nodes
  ansible.builtin.shell: |
    sudo tar czf - -C /opt/certificates . | \
      ssh -A -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
      {{ ansible_user | default('root') }}@{{ inventory_hostname }} \
      "sudo tar xzf - -C /opt/certificates"
  become: false
  delegate_to: "{{ swarm_leader }}"
  changed_when: false
