---
- name: Create secondemain-metabase directory
  file:
    path: /opt/secondemain-metabase
    state: directory

- name: Create secondemain-metabase files
  template:
    src: "{{ item }}.j2"
    dest: /opt/secondemain-metabase/{{ item }}
  with_items:
    - docker-compose.yml
    - secondemain-metabase.env

- name: Pull
  command: docker compose pull
  args:
    chdir: /opt/secondemain-metabase
  tags:
    - pull
  when: inventory_hostname == host_node

- name: Up
  command: docker stack deploy -c docker-compose.yml secondemain-metabase
  args:
    chdir: /opt/secondemain-metabase
  tags:
    - up
  when: is_swarm_leader | default(false)
