---
- name: Create secondemain-metabase directory
  file:
    path: "/opt/secondemain-metabase"
    state: directory

- name: Creating secondemain-metabase template
  template:
    src: "docker-compose.yml.j2"
    dest: /opt/secondemain-metabase/docker-compose.yml

- name: Pull
  command: docker compose pull
  args:
    chdir: /opt/secondemain-metabase
  tags:
    - pull

- name: Up
  command: docker compose up -d
  args:
    chdir: /opt/secondemain-metabase
  tags:
    - up
