---
reload_cmd: docker service update --force traefik_app
le_certs_dir: /opt/certificates
staging: False
notification_mail_from: le+room303@quickpipes.io
notification_mail_to: le+room303@quickpipes.io
force: False
scaleway_api_token: "{{ lookup('env', 'ACME_SH_SCW_TOKEN') }}"
