---
default_server_name: n8n.services.dataforgood.fr
d4g_n8n_install_dir: /opt/d4g-n8n

n8n_db_name: n8n
n8n_db_host: "{{ lookup('env', 'POLETECH_DB_HOST') }}"
n8n_db_port: "{{ lookup('env', 'POLETECH_DB_PORT') }}"
n8n_db_user: n8n
n8n_db_password: "{{ lookup('env', 'N8N_DB_PASSWORD') }}"

n8n_smtp_host: "{{ lookup('env', 'SMTP_HOST') }}"
n8n_smtp_port: "{{ lookup('env', 'SMTP_PORT_NUMBER') }}"
n8n_smtp_user: "{{ lookup('env', 'SMTP_USER') }}"
n8n_smtp_sender: "{{ lookup('env', 'SMTP_PASSWORD') }}"

n8n_encryption_key: "{{ lookup('env', 'N8N_ENCRYPTION_KEY') }}"
