---
- name: Create d4g-13-potentiel-solaire directory
  file:
    path: /opt/d4g-13-potentiel-solaire
    state: directory

- name: Create d4g-13-potentiel-solaire files
  template:
    src: "{{ item }}.j2"
    dest: /opt/d4g-13-potentiel-solaire/{{ item }}
  with_items:
    - docker-compose.yml
    - 13_potentiel_solaire.env

- name: Pull
  command: docker compose pull
  args:
    chdir: /opt/d4g-13-potentiel-solaire
  tags:
    - pull
  when: inventory_hostname == deploy_on

- name: Up
  command: docker stack deploy -c docker-compose.yml d4g-13-potentiel-solaire
  args:
    chdir: /opt/d4g-13-potentiel-solaire
  tags:
    - up
  when: is_swarm_leader | default(false)
