production_swarm_cluster_nodes:
  hosts:
    metal-1.dataforgood.fr:
      is_swarm_leader: true
      ip: 51.158.55.41
    metal-2.dataforgood.fr:
      ip: 51.159.221.12

staging_swarm_cluster_nodes:
  hosts:
    d4g-staging-01.d4g.fr:
      is_swarm_leader: true
      ip: 51.159.99.215
