---
- name: Create d4g-n8n directory
  file:
    path: /opt/d4g-n8n
    state: directory

- name: Create d4g-n8n files
  template:
    src: "{{ item }}.j2"
    dest: /opt/d4g-n8n/{{ item }}
  with_items:
    - docker-compose.yml
    - n8n.env

- name: Create d4g-n8n data directory
  file:
    path: /opt/d4g-n8n/data
    state: directory

- name: Pull
  command: docker compose pull
  args:
    chdir: /opt/d4g-n8n
  tags:
    - pull
  when: inventory_hostname == deploy_on

- name: Up
  command: docker stack deploy -c docker-compose.yml d4g-n8n
  args:
    chdir: /opt/d4g-n8n
  tags:
    - up
  when: is_swarm_leader | default(false)

- import_role:
    name: roles/utilities/s3-backup
  vars:
    service_name: n8n
    data_dir: /opt/d4g-n8n/data
  tags:
    - backup
    - service
  when: inventory_hostname == deploy_on
