---
- name: Create d4g-n8n directory
  file:
    path: "{{ d4g_n8n_install_dir }}"
    state: directory

- name: Creating d4g-n8n template
  template:
    src: "docker-compose.yml.j2"
    dest: /opt/d4g-n8n/docker-compose.yml

- name: Pull
  command: docker compose pull
  args:
    chdir: /opt/d4g-n8n
  tags:
    - pull

- name: Up
  command: docker compose up -d
  args:
    chdir: /opt/d4g-n8n
  tags:
    - up
