---
- name: Create d4g-moodle directory
  file:
    path: /opt/d4g-moodle
    state: directory

- name: Create d4g-moodle files
  template:
    src: "{{ item }}.j2"
    dest: /opt/d4g-moodle/{{ item }}
  with_items:
    - docker-compose.yml
    - moodle.env

- name: Create d4g-moodle data
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /opt/d4g-moodle/data
    - /opt/d4g-moodle/data/moodle
    - /opt/d4g-moodle/data/moodledata

- name: Pull
  command: docker compose pull
  args:
    chdir: /opt/d4g-moodle
  tags:
    - pull
  when: inventory_hostname == deploy_on

- name: Up
  command: docker stack deploy -c docker-compose.yml d4g-moodle
  args:
    chdir: /opt/d4g-moodle
  tags:
    - up
  when: is_swarm_leader | default(false)

- import_role:
    name: roles/utilities/s3-backup
  vars:
    service_name: moodle
    data_dir: /opt/d4g-moodle/data
  tags:
    - backup
    - service
  when: inventory_hostname == deploy_on

- import_role:
    name: roles/utilities/sql-backup
  vars:
    service: d4g-moodle
    service_dir: /opt/d4g-moodle
    pgsql_host: "{{ lookup('env', 'POLETECH_DB_HOST') }}"
    pgsql_port: "{{ lookup('env', 'POLETECH_DB_PORT') }}"
    pgsql_user: moodle
    pgsql_password: "{{ lookup('env', 'MOODLE_DATABASE_PASSWORD') }}"
    pgsql_database: moodle
  tags:
    - backup
    - service
  when: inventory_hostname == deploy_on
