---
- name: Create d4g-uptime-kuma directory
  file:
    path: "/opt/d4g-uptime-kuma"
    state: directory

- name: Create d4g-uptime-kuma data directory
  file:
    path: "/opt/d4g-uptime-kuma/data"
    state: directory

- name: Creating d4g-uptime-kuma template
  template:
    src: "docker-compose.yml.j2"
    dest: /opt/d4g-uptime-kuma/docker-compose.yml

- name: Pull
  command: docker compose pull
  args:
    chdir: /opt/d4g-uptime-kuma
  tags:
    - pull

- name: Up
  command: docker compose up -d
  args:
    chdir: /opt/d4g-uptime-kuma
  tags:
    - up
