---
- name: Create d4g-uptime-kuma directory
  file:
    path: "/opt/d4g-uptime-kuma"
    state: directory

- name: Create d4g-uptime-kuma data directory
  file:
    path: "/opt/d4g-uptime-kuma/data"
    state: directory

- name: Creating d4g-uptime-kuma template
  template:
    src: "{{ item }}.j2"
    dest: /opt/d4g-uptime-kuma/{{ item }}
  with_items:
    - docker-compose.yml
    - uptime-kuma.env

- name: Pull
  command: docker compose pull
  args:
    chdir: /opt/d4g-uptime-kuma
  tags:
    - pull
  when: inventory_hostname == deploy_on

- name: Up
  command: docker stack deploy -c docker-compose.yml d4g-uptime-kuma
  args:
    chdir: /opt/d4g-uptime-kuma
  tags:
    - up
  when: is_swarm_leader | default(false)

- import_role:
    name: roles/utilities/s3-backup
  vars:
    service_name: uptime-kuma
    data_dir: /opt/d4g-uptime-kuma/data
  tags:
    - backup
    - service
  when: inventory_hostname == deploy_on
