---
- name: Create us-climate-data-dispatcher directory
  file:
    path: /opt/us-climate-data-dispatcher
    state: directory

- name: Create us-climate-data-dispatcher files
  template:
    src: "{{ item }}.j2"
    dest: /opt/us-climate-data-dispatcher/{{ item }}
  with_items:
    - docker-compose.yml
    - us-climate-data-dispatcher.env

- name: Pull
  command: docker compose pull
  args:
    chdir: /opt/us-climate-data-dispatcher
  tags:
    - pull
  when: inventory_hostname == deploy_on

- name: Up
  command: docker stack deploy -c docker-compose.yml us-climate-data-dispatcher
  args:
    chdir: /opt/us-climate-data-dispatcher
  tags:
    - up
  when: is_swarm_leader | default(false)
