---
- name: Test nginx config before reloading
  command: docker run --rm --name nginx-test -v /opt/certificates:/opt/certificates -v /opt/d4g-proxy/nginx.conf:/etc/nginx/nginx.conf -v /opt/d4g-proxy/nginx-conf:/etc/nginx/conf.d/ nginx:1-alpine nginx -t
  register: nginx_test
  changed_when: false
  listen: "nginx config updated"

- name: Reload nginx container
  command: docker restart d4g-proxy
  when: nginx_test.rc == 0
  listen:
    - "nginx config updated"
