---
- name: Create d4g-proxy directory
  file:
    path: "/opt/d4g-proxy"
    state: directory

- name: Create docker-compose nginx configuration
  copy:
    src: nginx.conf
    dest: /opt/d4g-proxy/nginx.conf

- name: Creating d4g-proxy templates
  template:
    src: "docker-compose.yml.j2"
    dest: /opt/d4g-proxy/docker-compose.yml

- name: Cleanup services configurations
  file:
    state: absent
    path: /opt/d4g-proxy/nginx-conf/
  notify:
    - "nginx config updated"

- name: Create nginx-conf directory
  file:
    path: "/opt/d4g-proxy/nginx-conf"
    state: directory
    owner: 1000
    group: 1000

- name: Create services configurations
  template:
    src: "default.conf.j2"
    dest: /opt/d4g-proxy/nginx-conf/default.conf
  notify:
    - "nginx config updated"

- name: Create services configurations
  template:
    src: "service.conf.j2"
    dest: /opt/d4g-proxy/nginx-conf/{{ item.service_name }}.conf
  with_items:
    - {
        service_name: "vaultwarden",
        service_addresses: ["d4g-vaultwarden"],
        open_bar_cors: false,
      }
    - {
        service_name: "n8n",
        service_addresses: ["d4g-n8n"],
        open_bar_cors: false,
      }
    - {
        service_name: "uptime",
        service_addresses: ["d4g-uptime-kuma:8080"],
        open_bar_cors: false,
      }
    - {
        service_name: "outline",
        service_addresses: ["d4g-outline:3000"],
        open_bar_cors: false,
      }
    - {
        service_name: "secondemain",
        service_addresses: ["secondemain-metabase:3000"],
        open_bar_cors: false,
      }
  notify:
    - "nginx config updated"

# - name: Create static nginx configuration
#   copy:
#     src: static-nginx/{{ item }}
#     dest: /opt/d4g-proxy/nginx-conf/{{ item }}
#   with_items:
#     - room303.conf
#   notify:
#     - "nginx config updated"

- name: Pull
  command: docker compose pull
  args:
    chdir: /opt/d4g-proxy
  tags:
    - pull

- name: Up
  command: docker compose up -d
  args:
    chdir: /opt/d4g-proxy
  tags:
    - up
