---
- name: Create d4g-proxy directory
  file:
    path: /opt/d4g-proxy
    state: directory

- name: Create docker-compose nginx configuration
  copy:
    src: nginx.conf
    dest: /opt/d4g-proxy/nginx.conf

- name: Creating d4g-proxy templates
  template:
    src: docker-compose.yml.j2
    dest: /opt/d4g-proxy/docker-compose.yml

- name: Create nginx-conf directory
  file:
    path: /opt/d4g-proxy/nginx-conf
    state: directory
    owner: 1000
    group: 1000

- name: Create services configurations
  template:
    src: "default.conf.j2"
    dest: /opt/d4g-proxy/nginx-conf/default.conf
  vars:
    services:
      - name: "vaultwarden"
        addresses: ["d4g-vaultwarden_app"]
        open_bar_cors: false
      - name: "n8n"
        addresses: ["d4g-n8n_app"]
        open_bar_cors: false
      - name: "uptime"
        addresses: ["d4g-uptime-kuma_app"]
        open_bar_cors: false
      - name: "outline"
        addresses: ["d4g-outline_app"]
        open_bar_cors: false
      - name: "secondemain"
        addresses: ["secondemain-metabase_app:3000"]
        open_bar_cors: false
      - name: "moodle"
        addresses: ["d4g-moodle_app:8080"]
        open_bar_cors: false
      - name: "strapi"
        addresses: ["d4g-strapi_app:1337"]
        open_bar_cors: false
      - name: "noco"
        addresses: ["d4g-noco_app"]
        open_bar_cors: false
      - name: "people-api"
        addresses: ["d4g-people_backend"]
        open_bar_cors: false
      - name: "people"
        addresses: ["d4g-people_frontend"]
        open_bar_cors: false

# - name: Create static nginx configuration
#   copy:
#     src: static-nginx/{{ item }}
#     dest: /opt/d4g-proxy/nginx-conf/{{ item }}
#   with_items:
#     - room303.conf

- name: Pull
  command: docker compose pull
  args:
    chdir: /opt/d4g-proxy
  tags:
    - pull
  when: inventory_hostname == host_node

- name: Up
  command: docker stack deploy -c docker-compose.yml d4g-proxy
  args:
    chdir: /opt/d4g-proxy
  tags:
    - up
  when: is_swarm_leader | default(false)
