---
- name: Create d4g-proxy directory
  file:
    path: "/opt/d4g-proxy"
    state: directory

- name: Create docker-compose nginx configuration
  copy:
    src: nginx.conf
    dest: /opt/d4g-proxy/nginx.conf

- name: Creating d4g-proxy templates
  template:
    src: "docker-compose.yml.j2"
    dest: /opt/d4g-proxy/docker-compose.yml

- name: Create nginx-conf directory
  file:
    path: "/opt/d4g-proxy/nginx-conf"
    state: directory

- name: Create services configurations
  template:
    src: "default.conf.j2"
    dest: /opt/d4g-proxy/nginx-conf/default.conf
  notify:
    - "nginx config updated"

# - name: Create services configurations
#   template:
#     src: "service.conf.j2"
#     dest: /opt/d4g-proxy/nginx-conf/{{ item.service_name }}.conf
#   with_items:
#     - { service_name: "recofish", service_address: "51.159.144.205:8080" }
#   notify:
#     - "nginx config updated"

- name: Delete content & directory
  file:
    state: absent
    path: /opt/d4g-proxy/nginx-conf/{{ item.service_name }}.conf
  with_items:
    - { service_name: "recofish" }

- name: Pull
  command: docker compose pull
  args:
    chdir: /opt/d4g-proxy
  tags:
    - pull

- name: Up
  command: docker compose up -d
  args:
    chdir: /opt/d4g-proxy
  tags:
    - up
