---
# This role installs proxmox
- name: Remove packages
  package:
    name:
      - os-prober
    state: absent

- name: Install packages
  package:
    name:
      - gpg
    state: present

- name: Clean /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: "^127.0.1.1.*"
    owner: root
    group: root
    mode: "0644"
    state: absent

- name: Add host in /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: "^{{ ansible_all_ipv4_addresses[0] }}"
    owner: root
    group: root
    mode: "0644"
    state: present
    line: "{{ ansible_all_ipv4_addresses[0] }} {{ ansible_hostname }}"

- name: Set IPV4 sysctl
  ansible.posix.sysctl:
    sysctl_file: /etc/sysctl.d/proxmox.conf
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  loop:
    - { name: net.ipv4.conf.all.rp_filter, value: 1 }
    - { name: net.ipv4.icmp_echo_ignore_broadcasts, value: 1 }
    - { name: net.ipv4.ip_forward, value: 1 }

- name: Add proxmox gpg key
  get_url:
    url: "https://enterprise.proxmox.com/debian/proxmox-release-{{ ansible_distribution_release }}.gpg"
    dest: "/etc/apt/trusted.gpg.d/proxmox-release-{{ ansible_distribution_release }}.gpg"
    owner: root
    group: root
    mode: "0644"

- name: Add proxmoxve archive repository and update cache
  apt_repository:
    repo: "deb [arch=amd64] http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-no-subscription"
    state: present
    update_cache: true

- name: Remove repo
  file:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    state: absent

- name: Full upgrade
  apt:
    update_cache: true
    upgrade: full

- name: Install Proxmox and tools
  package:
    name:
      - proxmox-ve
      - ksm-control-daemon
      - locales-all
      - chrony
      - libguestfs-tools
    state: present

- name: Remove repo
  file:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    state: absent

- name: Reload networking
  command:
    cmd: ifreload -a

- name: Wait for Proxmox to come back online
  wait_for:
    port: 22
    host: "{{ ansible_host }}"
    timeout: 60

- name: Restart pve proxy
  service:
    name: pveproxy
    state: restarted
