---
- name: Create democis directory
  file:
    path: /opt/democis
    state: directory

- name: Create democis images directory
  file:
    path: "/opt/democis/images"
    state: directory

- name: Create democis files
  template:
    src: "{{ item }}.j2"
    dest: /opt/democis/{{ item }}
  with_items:
    - docker-compose.yml

- name: Create democis files
  ansible.builtin.copy:
    src: files/"{{ item }}"
    dest: /opt/democis/{{ item }}
  with_items:
    - index.html
    - images/1.jpg
    - images/2.jpg
    - images/3.jpg
    - images/4.jpg
    - images/cnrs.png
    - images/democis.png
    - images/france_2030.jpg
    - images/imt.png
    - images/inria.png
    - images/logo_longueur.png
    - images/logo_sur_fond_fonce.png
    - images/logo.png
    - logocarre.png
    - science-po.jpg
    - sciencespologo.png

- name: Pull
  command: docker compose pull
  args:
    chdir: /opt/democis
  tags:
    - pull
  when: inventory_hostname == deploy_on

- name: Up
  command: docker stack deploy -c docker-compose.yml democis
  args:
    chdir: /opt/democis
  tags:
    - up
  when: is_swarm_leader | default(false)

- import_role:
    name: roles/utilities/s3-backup
  vars:
    service_name: moodle
    data_dir: /opt/democis/data
  tags:
    - backup
    - service
  when: inventory_hostname == deploy_on

- import_role:
    name: roles/utilities/sql-backup
  vars:
    service: democis
    service_dir: /opt/democis
    pgsql_host: "{{ lookup('env', 'POLETECH_DB_HOST') }}"
    pgsql_port: "{{ lookup('env', 'POLETECH_DB_PORT') }}"
    pgsql_user: moodle
    pgsql_password: "{{ lookup('env', 'MOODLE_DATABASE_PASSWORD') }}"
    pgsql_database: moodle
  tags:
    - backup
    - service
  when: inventory_hostname == deploy_on
