---
- name: Create d4g-proxy
  hosts: cartovegetation_rdp
  remote_user: root

  tasks:
    - hostname:
        name: "carto-rdp-instance-{{ play_hosts.index(inventory_hostname) }}"

    - import_role:
        name: roles/utilities/base-pkg

    - import_role:
        name: roles/utilities/ssh-keys
      tags:
        - ssh

    - import_role:
        name: roles/services/cartovegetation-rdp
      tags:
        - service
