---
- name: Create d4g-proxy
  hosts: d4g_proxmox
  remote_user: root

  tasks:
      - import_role:
            name: roles/utilities/base-pkg
        tags:
            - base-pkg

      - import_role:
            name: roles/utilities/docker

      - import_role:
            name: roles/services/legislatives-circos
        tags:
            - service
            - legislatives

      # legislatives-circo runs on ports 3000. Let's make sure it's protected
      - import_role:
            name: roles/utilities/proxy-protect
        vars:
            proxy_ports: [8500, 8501, 8502, 8503]
        tags:
            - service
            - proxy-protect
            - legislatives

      - import_role:
            name: roles/utilities/deploy-cron
        vars:
            service_name: "legislatives"
            repo_canonical_name: "dataforgoodfr/legislatives_2024_circos"
            deploy_cron_location: "/opt/legislatives_2024_circos/bin/deploy_cron"
        tags:
            - deploy-cron
            - service
            - legislatives

      - import_role:
            name: roles/services/secondemain-metabase
        tags:
            - service
            - secondemain

      # secondemain-metabase runs on port 3000. Let's make sure it's protected
      - import_role:
            name: roles/utilities/proxy-protect
        vars:
            proxy_ports: [3000]
        tags:
            - service
            - proxy-protect
            - secondemain
