---
- name: Initial configuration
  hosts: metal-2.dataforgood.fr
  remote_user: ubuntu
  become: true

  tasks:
      - import_role:
            name: roles/utilities/base-ubuntu
        tags:
            - base-ubuntu

- name: Create metal-2
  hosts: metal-2.dataforgood.fr
  remote_user: root

  tasks:
      - import_role:
            name: roles/utilities/docker
        vars:
            use_swarm: true
        tags:
            - docker

      - import_role:
            name: roles/services/d4g-uptime-kuma
        tags:
            - uptime-kuma
            - service

      - import_role:
            name: roles/utilities/s3-backup
        vars:
            service_name: uptime-kuma
            data_dir: /opt/d4g-uptime-kuma/data
        tags:
            - backup
            - service

      - import_role:
            name: roles/services/d4g-outline
        tags:
            - outline
            - service
