---
- name: Initial configuration
  hosts: metal-1.dataforgood.fr
  remote_user: ubuntu
  become: true

  tasks:
    - import_role:
        name: roles/utilities/base-ubuntu
      tags:
        - base-ubuntu

- name: Create metal-1
  hosts: metal-1.dataforgood.fr
  remote_user: root

  tasks:
    - import_role:
        name: roles/utilities/docker
      vars:
        use_swarm: true
        is_swarm_leader: true
      tags:
        - docker

    - import_role:
        name: roles/utilities/acme.sh
      vars:
        domain_names:
          - "*.services.dataforgood.fr"
        reload_cmd: docker exec d4g-proxy nginx -s reload
        notification_mail_from: proxyd4g@dataforgood.fr
        notification_mail_to: proxyd4g@quickpipes.io
      tags:
        - acme

    - import_role:
        name: roles/services/d4g-vaultwarden
      tags:
        - vaultwarden
        - service

    - import_role:
        name: roles/utilities/s3-backup
      vars:
        service_name: vaultwarden
        data_dir: /opt/d4g-vaultwarden/data
      tags:
        - backup
        - service

    - import_role:
        name: roles/services/d4g-n8n
      tags:
        - n8n
        - service

    - import_role:
        name: roles/utilities/s3-backup
      vars:
        service_name: n8n
        data_dir: /opt/d4g-n8n/data
      tags:
        - backup
        - service

    - import_role:
        name: roles/services/secondemain-metabase
      tags:
        - secondemain
        - saison

    - import_role:
        name: roles/services/d4g-proxy
      tags:
        - proxy
        - service
