---
- name: Initial configuration
  hosts: staging_swarm_cluster_nodes
  remote_user: ubuntu
  become: true

  tasks:
    - import_role:
        name: roles/utilities/base-ubuntu
      vars:
        d4gctl_environment: staging
      tags:
        - base

- name: Create swarm workers
  hosts: staging_swarm_cluster_nodes
  remote_user: root

  tasks:
    - import_role:
        name: roles/utilities/docker
      vars:
        use_swarm: true
        group_name: "staging_swarm_cluster_nodes"
      tags:
        - docker
        - utils

- name: Create swarm applications
  hosts: staging_swarm_cluster_nodes
  remote_user: root

  vars:
    # Staging environment overrides
    base_domain: services.d4g.fr
    backup_s3_bucket: poletech-backups-staging
    loki_s3_bucket: poletech-logs-staging
    outline_s3_bucket: outline-uploads-staging
    authentik_s3_bucket: authentik-uploads-staging


  tasks:
    - import_role:
        name: roles/utilities/acme.sh
      vars:
        group_name: "staging_swarm_cluster_nodes"
        certificates:
          - name: services.d4g.fr
            domains:
              - "*.services.d4g.fr"
          - name: d4g.fr
            domains:
              - "d4g.fr"
              - "*.d4g.fr"
      tags:
        - acme
        - tls

    - import_role:
        name: roles/services/shared-postgresql
      vars:
        deploy_on: "d4g-staging-01.d4g.fr"
        postgres_root_password: "{{ lookup('env', 'POSTGRES_ROOT_PASSWORD') }}"
        observability_password: "{{ lookup('env', 'POSTGRES_OBSERVABILITY_PASSWORD') }}"
        databases:
          - db: outline
            user: outline
            password: "{{ lookup('env', 'OUTLINE_DB_PASSWORD') }}"
          - db: mattermost
            user: mattermost
            password: "{{ lookup('env', 'MATTERMOST_DB_PASSWORD') }}"
          - db: authentik
            user: authentik
            password: "{{ lookup('env', 'AUTHENTIK_DB_PASSWORD') }}"
          - db: peertube
            user: peertube
            password: "{{ lookup('env', 'PEERTUBE_DB_PASSWORD') }}"
          - db: visio
            user: visio
            password: "{{ lookup('env', 'VISIO_DB_PASSWORD') }}"
          - db: grist
            user: grist
            password: "{{ lookup('env', 'GRIST_DB_PASSWORD') }}"
          - db: community_manager
            user: community_manager
            password: "{{ lookup('env', 'HOME_DB_PASSWORD') }}"
          - db: docs
            user: docs
            password: "{{ lookup('env', 'DOCS_DB_PASSWORD') }}"
      tags:
        - postgresql
        - database
        - service

    - import_role:
        name: roles/services/d4g-outline
      vars:
        deploy_on: "d4g-staging-01.d4g.fr"
        replicas: 1
      tags:
        - outline
        - service

    - import_role:
        name: roles/services/d4g-mattermost
      vars:
        deploy_on: "d4g-staging-01.d4g.fr"
        replicas: 1
        mattermost_image_tag: "10.11.14"
      tags:
        - mattermost
        - service

    - import_role:
        name: roles/services/d4g-authentik
      vars:
        deploy_on: "d4g-staging-01.d4g.fr"
        replicas: 1
      tags:
        - authentik
        - service

    - import_role:
        name: roles/services/d4g-community-manager
      vars:
        deploy_on: "d4g-staging-01.d4g.fr"
        replicas: 1
      tags:
        - d4g-community-manager
        - service

    - import_role:
        name: roles/services/theconversation-peertube
      vars:
        deploy_on: "d4g-staging-01.d4g.fr"
        replicas: 1
      tags:
        - theconversation-peertube
        - service

    - import_role:
        name: roles/services/d4g-coolify
      vars:
        deploy_on: "d4g-staging-01.d4g.fr"
        replicas: 1
      tags:
        - d4g-coolify
        - service

    - import_role:
        name: roles/services/d4g-visio
      vars:
        deploy_on: "d4g-staging-01.d4g.fr"
        replicas: 1
      tags:
        - visio
        - service

    - import_role:
        name: roles/services/d4g-grist
      vars:
        deploy_on: "d4g-staging-01.d4g.fr"
        replicas: 1
        grist_s3_bucket: grist-docs-staging
      tags:
        - d4g-grist
        - service

    - import_role:
        name: roles/services/d4g-home
      vars:
        deploy_on: "d4g-staging-01.d4g.fr"
        replicas: 1
        home_base_url: "https://home.d4g.fr"
      tags:
        - d4g-home
        - service

    - import_role:
        name: roles/services/d4g-docs
      vars:
        deploy_on: "d4g-staging-01.d4g.fr"
        replicas: 1
        docs_s3_bucket: docs-uploads-staging
      tags:
        - d4g-docs
        - service

    - import_role:
        name: roles/utilities/observability
      vars:
        group_name: staging_swarm_cluster_nodes
        observability_cluster_name: d4g-staging
        observability_environment: staging
        observability_remote_write_url: "https://victoriametrics.services.dataforgood.fr/api/v1/write"
        observability_remote_write_basic_auth_username: "{{ lookup('env', 'VICTORIAMETRICS_WRITE_USER') }}"
        observability_remote_write_basic_auth_password: "{{ lookup('env', 'VICTORIAMETRICS_WRITE_PASSWORD') }}"
      tags:
        - observability
        - utils

    - import_role:
        name: roles/utilities/traefik
      vars:
        certificates:
          - name: services.d4g.fr
            domains:
              - "*.services.d4g.fr"
          - name: d4g.fr
            domains:
              - "d4g.fr"
              - "*.d4g.fr"
        services:
          - name: "outline"
            addresses: ["d4g-outline_app"]
          - name: "risefor-admin"
            addresses: ["risefor-backend-1:8000"]
          - name: "risefor-frontend"
            addresses: ["risefor-orbit-1:5174"]
          - name: "coolify"
            addresses: ["d4g-coolify_coolify:8080"]
          - name: "coolify-realtime"
            rule: "Host(`coolify.services.d4g.fr`) && (PathPrefix(`/app`) || PathPrefix(`/socket.io`))"
            addresses: ["d4g-coolify_coolify-realtime:6001"]
          - name: "authentik"
            addresses: ["d4g-authentik_app"]
          - name: "mattermost"
            addresses: ["d4g-mattermost_app:8065"]
          - name: "grafana"
            addresses: ["observability_grafana:3000"]
          - name: "theconversation-peertube"
            addresses: ["theconversation-peertube_app:9000"]
          - name: "visio"
            addresses: ["d4g-visio_frontend:8083"]
          - name: "livekit-visio"
            addresses: ["d4g-visio_livekit:7880"]
          - name: "grist"
            addresses: ["d4g-grist_app:8484"]
          - name: "home"
            addresses: ["d4g-home_app:8000"]
            override_name: "home.d4g.fr"
          - name: "docs"
            addresses: ["d4g-docs_frontend:8083"]
      tags:
        - proxy
        - traefik
        - service
