---
- name: Create d4g-vaultwarden directory
  file:
    path: "{{ d4g_vaultwarden_install_dir }}"
    state: directory

- name: Creating d4g-vaultwarden template
  template:
    src: "docker-compose.yml.j2"
    dest: /opt/d4g-vaultwarden/docker-compose.yml
