---
- name: Create d4g-vaultwarden directory
  file:
    path: /opt/d4g-vaultwarden
    state: directory

- name: Create d4g-vaultwarden files
  template:
    src: "{{ item }}.j2"
    dest: /opt/d4g-vaultwarden/{{ item }}
  with_items:
    - docker-compose.yml
    - vaultwarden.env

- name: Pull
  command: docker compose pull
  args:
    chdir: /opt/d4g-vaultwarden
  tags:
    - pull
  when: inventory_hostname == deploy_on

- name: Up
  command: docker stack deploy -c docker-compose.yml d4g-vaultwarden
  args:
    chdir: /opt/d4g-vaultwarden
  tags:
    - up
  when: is_swarm_leader | default(false)

- import_role:
    name: roles/utilities/s3-backup
  vars:
    service_name: vaultwarden
    data_dir: /opt/d4g-vaultwarden/data
  tags:
    - backup
    - service
  when: inventory_hostname == deploy_on

- import_role:
    name: roles/utilities/sql-backup
  vars:
    service: d4g-vaultwarden
    service_dir: /opt/d4g-vaultwarden
    pgsql_host: "{{ lookup('env', 'POLETECH_DB_HOST') }}"
    pgsql_port: "{{ lookup('env', 'POLETECH_DB_PORT') }}"
    pgsql_user: vaultwarden
    pgsql_password: "{{ lookup('env', 'VAULTWARDEN_DB_PASSWORD') }}"
    pgsql_database: vaultwarden
  tags:
    - backup
    - service
  when: inventory_hostname == deploy_on
