---
- name: Create datadog-agent directory
  file:
    path: /opt/datadog-agent
    state: directory

- name: Create datadog-agent data directory
  file:
    path: /opt/datadog-agent/data/run
    state: directory

- name: Creating datadog-agent template
  template:
    src: "{{ item }}.j2"
    dest: "/opt/datadog-agent/{{ item }}"
  with_items:
    - "docker-compose.yml"
    - "datadog.env"

- name: Pull
  command: docker compose pull
  args:
    chdir: /opt/datadog-agent
  tags:
    - pull

- name: Up
  command: docker stack deploy -c docker-compose.yml datadog-agent
  args:
    chdir: /opt/datadog-agent
  tags:
    - up
  when: is_swarm_leader | default(false)
