---
- name: Clone github repo in SSH
  git:
    repo: "git@github.com:dataforgoodfr/legislatives_2024_circos.git"
    dest: "/opt/legislatives_2024_circos"

- name: Pull
  command: docker compose pull
  args:
    chdir: /opt/legislatives_2024_circos
  tags:
    - pull

- name: Up
  command: docker compose up -d
  args:
    chdir: /opt/legislatives_2024_circos
  tags:
    - up
